#!/bin/bash

echo "GitHub Secrets Setup Script"
echo "============================"
echo ""
echo "You need to add these secrets manually at:"
echo "https://github.com/dashaaaa21/3D-configurator/settings/secrets/actions"
echo ""
echo "Required secrets:"
echo ""
echo "1. VERCEL_TOKEN"
echo "   Get from: https://vercel.com/account/tokens"
echo "   Click 'Create Token', name it 'GitHub Actions'"
echo ""
echo "2. VERCEL_ORG_ID"
echo "   Run: vercel link"
echo "   Then: cat .vercel/project.json | grep orgId"
echo ""
echo "3. VERCEL_PROJECT_ID"
echo "   Run: vercel link"
echo "   Then: cat .vercel/project.json | grep projectId"
echo ""
echo "4. RENDER_DEPLOY_HOOK_URL"
echo "   Go to: https://dashboard.render.com/web/srv-d5htj475r7bs73bmh080"
echo "   Settings → Deploy Hook → Create Deploy Hook"
echo ""
echo "After adding all secrets, run:"
echo "git push origin main"
echo ""
