services:
  - type: web
    name: threejs-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://3-d-configurator-omega.vercel.app
    healthCheckPath: /
    autoDeploy: true
